# Generated by Django 2.2.7 on 2020-01-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provideapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='empid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
