# Generated by Django 3.0.2 on 2020-02-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provideapi', '0003_auto_20200205_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(choices=[('BOSTON', 'BOSTON'), ('NEWYORK', 'NEWYORK')], default='BOSTON', max_length=19),
        ),
    ]
