# Generated by Django 3.0.2 on 2020-02-05 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provideapi', '0004_employee_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provideapi.Location'),
        ),
    ]
