# Generated by Django 3.0.2 on 2020-02-05 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provideapi', '0005_auto_20200205_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='location',
        ),
    ]
