# Generated by Django 3.0.2 on 2020-02-05 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provideapi', '0008_remove_employee_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='provideapi.Location'),
            preserve_default=False,
        ),
    ]
