# Generated by Django 3.0.2 on 2020-02-06 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provideapi', '0009_employee_location'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='provideapi.Location'),
        ),
    ]

