# Generated by Django 3.0.2 on 2020-02-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provideapi', '0010_auto_20200206_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
